### ISSUE TITLE
Vortex slowdown

### ISSUE THREAD

**Issue by ronamit** [agc93/vortex-showcase#13]
Vortex 1.3.17
Showcase extension version 0.1.6

When I create a showcase ( in any format), Vortex sometimes seems to almost freeze and has high CPU usage.
If I wait  2 minutes it passes.

This is the latest modwat showcase
https://modwat.ch/u/RON4A1/modlist

**Comment by agc93** [comment]
I'll have a look for areas I might be able to optimise things but with a mod list **that** long, some slowdown is just to be expected. 

Because of how both Showcase and Vortex work, Showcase needs to loop through every entry in your mods list one-by-one and build the report you eventually see. I'll definitely have a look and see if I can speed things up, but with over 600 mods to get through, there's no magic fix there.

**Comment by agc93** [comment]
@ronamit These slowdowns should now be resolved in v0.2.1 (only available for Vortex 1.4+).

If you're on testing updates, you should get that update automatically now, otherwise you'll get the update once Vortex 1.4 reaches stable release.
