### ISSUE TITLE
modwat is missing since last update

### ISSUE THREAD

**Issue by ronamit** [agc93/vortex-showcase#19]
I couldn't find the modwat option in version 0.2.0

**Comment by agc93** [comment]
Which extension are you trying to install and what version of Vortex are you using?

Since I couldn't test it, the [v0.2.0 version of Vortex Showcase](https://showcase.vortex.support/updates/v0.2.0) is only available for Vortex 1.4 (currently in beta), but the previous [v0.1.6](https://showcase.vortex.support/updates/v0.1.6) will still be available for earlier Vortex versions.

The Modwatch extension itself shouldn't have changed at all: its last update was late last year.

**Comment by ronamit** [comment]
I use Vortex 1.4.2 pre-release, Vortex Showcase 0.2.0, and Showcase  Extended Formats 0.0.3
The "Create mod showcase" menu shows these options:
![image](https://user-images.githubusercontent.com/23059549/108715009-f2561e00-7522-11eb-8180-2988dc48a239.png)

**Comment by agc93** [comment]
Oh, since Modwatch wasn't compatible with the first alpha of 1.4, make sure that the "Modwatch for Vortex" extension is still installed *and enabled* in your Vortex extensions pane. If it's not there, reinstall it and try again, you should see the "Upload to Modwat.ch" buttons appear in the top toolbar for supported games.

**Comment by ronamit** [comment]
I can't find the "Modwatch for Vortex" extension in my in the "Browse Extensions" menu, or in the installed extensions.
I installed it manually and now it works.
Thanks!

**Comment by agc93** [comment]
This was caused by a bug in Nexus Mod's updater, but they've apparently fixed it now so it should show up in the browser as expected.
